version: '3.8'

services:
  web:
    build: .
    ports:
      - "80000:80000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CASHFREE_APP_ID=${CASHFREE_APP_ID}
      - CASHFREE_SECRET_KEY=${CASHFREE_SECRET_KEY}
      - CASHFREE_ENV=${CASHFREE_ENV}
    env_file:
      - .env
